### PR TITLE
Fixed mapping MGL enum values on RN 0.59

### LINKED ISSUE #78: App crashes when using enums (lineCap/lineJoin/iconAnchor etc) with RN 0.59
**Describe the bug**
App crashes when using enum values with latest react-native / 0.59 with the following error:

```
Assertion failed: (it != std::end(MGLLineCap_names)), function toString, file /Users/distiller/project/platform/darwin/src/MGLLineStyleLayer.mm, line 23.
````

This issue is similar to this PR: https://github.com/nitaliano/react-native-mapbox-gl/pull/1593

**To Reproduce**
Create a line layer and apply a linecap style: `lineCap: MapboxGL.LineJoin.Round,`

**Expected behavior**
App doesn't crash

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhonse SE (Simulator)
 - OS: iOS12.1
 - Deployment Target: 9.1
 - React Native Version 0.59.0

### PR DESCRIPTION
**Pull request by mattijsf**
Fixes #78 

There was a similar issue in the legacy repo. This is the same fix. I tested it using the Example app by adding the lineCap to one of the examples.

### CODE REVIEW

File: ios/RCTMGL/RCTMGLStyleValue.m [hunk 1]
```diff
@@ -30,6 +30,12 @@ - (NSExpression *)mglStyleValue
     } else if ([_styleType isEqual:@"edgeinsets"] && [expressionJSON isKindOfClass:[NSNumber class]]){
         UIEdgeInsets edgeInsets = [RCTMGLUtils toUIEdgeInsets:(NSArray<NSNumber *> *)expressionJSON];
         return [NSExpression expressionWithMGLJSONObject:[NSValue valueWithUIEdgeInsets:edgeInsets]];
+    } else if ([_styleType isEqualToString:@"enum"] && [expressionJSON isKindOfClass:[NSNumber class]]) {
+        UIColor *color = [RCTMGLUtils toColor:expressionJSON];
```
Comment (mfazekas) [inline ios/RCTMGL/RCTMGLStyleValue.m]: do we use the color?

Comment (mattijsf) [reply ios/RCTMGL/RCTMGLStyleValue.m]: Whoops that slipped right in. Sorry for that.

**Comment by mattijsf** [comment]
This PR/fix was also mentioned by @kristfal here https://github.com/react-native-mapbox-gl/maps/issues/31#issuecomment-490865508
