### PR TITLE
fix(user-location): fix crash issue when using androidRenderMode

### LINKED ISSUE #1022: App crash with Error: Error While updating property 'androidRenderMode' of view managed by: RCTMGLNativeUserLocation null
**Describe the bug**

crashes the app with Error: Error While updating property 'androidRenderMode' of view managed by: RCTMGLNativeUserLocation null
Attemt to invoke virtual method 'com.mapbox.rctmgl.components.location.LocationComponentManager com.mapbox.rctmgl.components.mapview.RCTMGLMapView.getLocationComponentManager()' on null object reference.

**To Reproduce**
just added renderMode={'native'}   and  androidRenderMode={'compass'} to the UserLocation Component
Example:
```
 <MapboxGL.UserLocation renderMode={'native'} 
                                           androidRenderMode={'compass'}
                                           showsUserHeadingIndicator={true} 
                                           visible={true} 
                                           animated={true} />
```

**Expected behavior**
expect to show the native android location with moving heading

**Screenshots**

**Versions (please complete the following information):**
 - Platform: [Android]
 - Device: [Samsung Galaxy S10+]
 - Emulator/ Simulator: [no]
 - OS: [android]
 - react-native-mapbox-gl Version [^8.1.0-rc.4]
 - React Native Version [0.61.5]

**Additional context**

### PR DESCRIPTION
**Pull request by ferdicus**
App crashes when user is trying to set `androidRenderMode` as described in issue #1022.

I think I've tracked it down to a missing non-null check in `NativeUserLocation`.
In `setRenderMode` it attempts to call `getLocationComponentManager` on `mMapView` which seems to be `null` at that point in time.

This change fixes the crash. 

Two more things I noticed though:
* no types for `androidRenderMode` in `index.d.ts` (which I will address with a follow-up PR)
* the heading indicator doesn't seem to change when using `androidRenderMode="compass"`(from the short test I did 🤷 )

Feedback appreciated, thanks 🙇 

----

this resolves #1022

### CODE REVIEW

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java [hunk 1]
```diff
@@ -56,7 +56,9 @@ public void onStyleLoaded(@NonNull Style style) {
     }
 
     public void setRenderMode(@RenderMode.Mode int renderMode) {
-        LocationComponentManager locationComponent = mMapView.getLocationComponentManager();
-        locationComponent.setRenderMode(renderMode);
+        if (mMap != null) {
```
Comment (mfazekas) [inline android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: I think we might want to emit some error.  As the renderMode change will be lost in such case. (Either we need to store the desired mode and set when the map is attached. When logging please use `com.mapbox.mapboxsdk.log.Logger` as that gets transferred to js side.

**Review by mfazekas — CHANGES_REQUESTED** [review]
👍

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java (hunk 1 above)
Comment (ClayC-WeatherBug) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: Any idea on the cause of why mMap is null when setRenderMode is being called?

Comment (ferdicus) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: @mfazekas, just want to make sure I understand it correctly. 
If I should log when `mMap != null`, then it would mean we would indeed have an error every time `androidRenderMode` is used.

I was able to reproduce this 100% without much hassle. 

Wouldn't this be super annoying?

Maybe I'm mistaken

Comment (ferdicus) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: @ClayC-WeatherBug:
Unsure what is causing this - I would assume there are all sorts of race conditions happening. 🤷‍♂️ 
We have quite some `mMap == null` checks in source unfortunately :(

Comment (ClayC-WeatherBug) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: Ah dang - okay that makes sense. So this will get called repeatedly until mMap is not null and then it will set the render mode?

Comment (ferdicus) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: > Ah dang - okay that makes sense. So this will get called repeatedly until mMap is not null and then it will set the render mode?

yes... hopefully :D

Comment (ClayC-WeatherBug) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: Works for me 👍

**Review by ClayC-WeatherBug — APPROVED** [review]

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java (hunk 1 above)
Comment (mfazekas) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: So first react builds the components, the compontents added to parent MapView, at that point `mMapView` becomes non-null, and later when the Mapbox map in map view is initialized onMapReady is called and `mMap` becomes non-null.

But looking at the crash the reason for the crash is because `mMapView` is null, but this fix checks for `mMap`, why?!

Comment (ferdicus) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: yeah, you're right - I checked for map indiscriminately, should be more specific.

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java [hunk 2]
```diff
@@ -56,7 +56,9 @@ public void onStyleLoaded(@NonNull Style style) {
     }
 
     public void setRenderMode(@RenderMode.Mode int renderMode) {
-        LocationComponentManager locationComponent = mMapView.getLocationComponentManager();
-        locationComponent.setRenderMode(renderMode);
+        if (mMapView != null) {
```
Comment (mfazekas) [inline android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: If we don't have mMapView we should store `renderMode` in a variable and set it when we finally have `MapView`. Otherwise it'll be just lost.

**Review by mfazekas — CHANGES_REQUESTED** [review]

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java (hunk 2 above)
Comment (ferdicus) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: Thanks, where do you think would be a good spot to do that?

Should I maybe check in `#addToMap` if we have a `renderMode` set and then call `#setRenderMode` with it?
Or is there a better approach?

Comment (mfazekas) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:59]: Yep i think `addToMap` would be a good place to check. We have something similar with `RCTMGLCamera` with `MaxBounds` for example.


https://github.com/react-native-mapbox-gl/maps/blob/189213ffdf21ce47705eb809f24e44a1ed772de8/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java#L128-L133

https://github.com/react-native-mapbox-gl/maps/blob/189213ffdf21ce47705eb809f24e44a1ed772de8/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java#L167-L177

https://github.com/react-native-mapbox-gl/maps/blob/189213ffdf21ce47705eb809f24e44a1ed772de8/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCameraManager.java#L56-L62

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java [hunk 3]
```diff
@@ -28,6 +29,7 @@ public void addToMap(RCTMGLMapView mapView) {
         mEnabled = true;
         mMapView = mapView;
         mapView.getMapAsync(this);
+        if (mRenderMode < 0) { setRenderMode(mRenderMode); }
```
Comment (mfazekas) [inline android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:32]:
```suggestion
        if (mRenderMode >= 0) { setRenderMode(mRenderMode); }
```

**Review by mfazekas — CHANGES_REQUESTED** [review]
Looks great, but i think there is a typo

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java (hunk 3 above)
Comment (ferdicus) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:32]: 🤦‍♂️

**Comment by ferdicus** [comment]
Can you please have another look. 

Quick question, always eager to learn over here:
I had to loosen the type a bit, in order to initialize the int with `-1` which is not defined in `RenderMode`
Would there have been another way to do this, without losing `@RenderMode.Mode`?

**Comment by mfazekas** [comment]
> Quick question, always eager to learn over here:
> I had to loosen the type a bit, in order to initialize the int with `-1` which is not defined in `RenderMode`
> Would there have been another way to do this, without losing `@RenderMode.Mode`?

I'm not a java expert so not 100% on this. 

You might be able to use java.lang.Integer which allows null. 
Or just use a default - note sure what's would be appropriate in this case.

**Comment by ferdicus** [comment]
I'm going with this:
> Or just use a default - note sure what's would be appropriate in this case.

We're doing something similar [here](https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/LocationComponentManager.java#L37)

keeps type in tact

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java [hunk 4]
```diff
@@ -28,6 +29,7 @@ public void addToMap(RCTMGLMapView mapView) {
         mEnabled = true;
         mMapView = mapView;
         mapView.getMapAsync(this);
+        if (mRenderMode >= 0) { setRenderMode(mRenderMode); }
```
Comment (mfazekas) [inline android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java:32]:
```suggestion
       setRenderMode(mRenderMode);
```

**Review by mfazekas — APPROVED** [review]

File: android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java (hunk 4 above)
Comment (ferdicus) [reply android/rctmgl/src/main/java/com/mapbox/rctmgl/components/location/RCTMGLNativeUserLocation.java]: 😭
