### PR TITLE
#236 iOS Snapshotter as __block variable

### LINKED ISSUE #236: [IOS] snapshotManager.takeSnap() doesn't work
**Describe the bug**
When i use MapboxGL.snapshotManager.takeSnap(options) i get this error:
`Error: Could not create snapshot`

The error comes from this function in [MGLSnapshotModule.m](https://github.com/react-native-mapbox-gl/maps/blob/master/ios/RCTMGL/MGLSnapshotModule.m)
and there is no script for **MGLMapSnapshotter** in the repo.

```
RCT_EXPORT_METHOD(takeSnap:(NSDictionary *)jsOptions
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
    dispatch_async(dispatch_get_main_queue(), ^{
        MGLMapSnapshotOptions *options = [self _getOptions:jsOptions];
        MGLMapSnapshotter *snapshotter = [[MGLMapSnapshotter alloc] initWithOptions:options];
        
        [snapshotter startWithCompletionHandler:^(MGLMapSnapshot *snapshot, NSError *err) {
            if (err != nil) {
                reject(@"takeSnap", @"Could not create snapshot", err);
                return;
            }
            
            NSString *result = nil;
            if ([jsOptions[@"writeToDisk"] boolValue]) {
                result = [RNMBImageUtils createTempFile:snapshot.image];
            } else {
                result = [RNMBImageUtils createBase64:snapshot.image];
            }
            
            resolve(result);
        }];
    });
}
```

**To Reproduce**
Just try to take a snapshot with snapshot manager.

**Expected behavior**
It should return an uri or a base64 file

**Versions (please complete the following information):**
 - Platfrom: iOS
 - React Native Version 0.59
 - SDK: 7.0.0-rc3

### PR DESCRIPTION
**Pull request by kristfal**
Fixes #236.

### CODE REVIEW

File: ios/RCTMGL/MGLSnapshotModule.m [hunk 1]
```diff
@@ -42,6 +42,7 @@ + (BOOL)requiresMainQueueSetup
             }
             
             resolve(result);
+            snapshotter = nil;
```
Comment (mfazekas) [inline ios/RCTMGL/MGLSnapshotModule.m]: I guess we need to release in `err != nil` branch too.

File: ios/RCTMGL/MGLSnapshotModule.m [hunk 2]
```diff
@@ -24,11 +24,11 @@ + (BOOL)requiresMainQueueSetup
...
         MGLMapSnapshotOptions *options = [self _getOptions:jsOptions];
-        MGLMapSnapshotter *snapshotter = [[MGLMapSnapshotter alloc] initWithOptions:options];
-        
-        [snapshotter startWithCompletionHandler:^(MGLMapSnapshot *snapshot, NSError *err) {
+        __block MGLMapSnapshotter *snapshotter = [[MGLMapSnapshotter alloc] initWithOptions:options];
+
+        [snapshotter startWithCompletionHandler:^(MGLMapSnapshot * _Nullable snapshot, NSError * _Nullable err) {         
             if (err != nil) {
                 reject(@"takeSnap", @"Could not create snapshot", err);
                 return;
```
Comment (mfazekas) [inline ios/RCTMGL/MGLSnapshotModule.m]:
```suggestion
                snapshotter = nil;
                return;
```

File: ios/RCTMGL/MGLSnapshotModule.m (hunk 1 above)
Comment (kristfal) [reply ios/RCTMGL/MGLSnapshotModule.m]: Good catch, thanks.
