### PR TITLE
Make query filter parameters consistent with JS API

### LINKED ISSUE #431: Filtering does not work on `queryRenderedFeaturesAtPoint` or `queryRenderedFeaturesInRect`.
**Describe the bug**
When querying a mapbox layer by using either `MapView.queryRenderedFeaturesAtPoint` or `MapView.queryRenderedFeaturesInRect` everything works fine as long as no filter is passed but as soon as a filter is used the application crashes.

**To Reproduce**
In the example, `queryWithRect.js` replace `null` by `['==', 'type', 'Point']` in line 51 and run the example.

**Expected behavior**
I would expect an empty `featureCollection` as none of the features on `nyc_geojson.json` file have a property named `type`, but instead the application crashes.

**Screenshots**
Simulator Screen Shot - iPhone X - 2019-09-27 at 15 07 50

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone X
 - OS: iOS 12.2
 - SDK Version 7.0.4
 - React Native Version 0.60.5

**Additional context**
I was able to pinpoint a fix to this issue but I have zero confidence that this is the right solution due that I'm new to react-native and have zero knowledge of objective-c. In any case,  in `ios/RCTMGL/RCTMGLMapViewManager.m` I replaced `withFilter:(NSArray<NSDictionary<NSString *, id> *> *)filter` by `withFilter:(NSArray *)filter`

The changes in #173 even when related to a different filtering issue pointed me into my supposed "fix". Filtering queries is of tremendous importance for our team and in the meantime, we are linear searching the features that we need.

Thanks in advance and keep the good job.

### PR DESCRIPTION
**Pull request by chrisparton1991**
Issue #431 is occurring because of a mismatch in the JS->iOS bridge. The JS API accepts an array of strings for the query filter, but the iOS API was expecting an array of dictionaries.

This caused the bridging code to throw an error whenever a non-null filter array was passed in.

I'm not an iOS developer by trade, nor am I super familiar with this library, so there might be more work to do. That said, this change fixes #431 for me.

Closes: #431

### CODE REVIEW

File: ios/RCTMGL/RCTMGLMapViewManager.m [hunk 1]
```diff
@@ -209,7 +209,7 @@ - (UIView *)view
 
 RCT_EXPORT_METHOD(queryRenderedFeaturesAtPoint:(nonnull NSNumber*)reactTag
                   atPoint:(NSArray<NSNumber*>*)point
-                  withFilter:(NSArray<NSDictionary<NSString *, id> *> *)filter
+                  withFilter:(NSArray<NSString*>*)filter
```
Comment (mfazekas) [inline ios/RCTMGL/RCTMGLMapViewManager.m]: filter can be more complex with  `['==',['get','name'],'foo']`  so let's use just `NSArray*` instead of `NSArray<...>*`

Comment (chrisparton1991) [reply ios/RCTMGL/RCTMGLMapViewManager.m]: Ah right, nice catch. I've updated the PR.

**Comment by chrisparton1991** [comment]
@mfazekas @kristfal I hate to be that guy, but do you have a rough idea on when the next release will be ready?

It's not super urgent for me, but if I can have a loose date to give to my client that would be nice.

Appreciate all your hard work on the library!
