### PR TITLE
fix(Camera):allow all config changes to affect the camera and update example

### LINKED ISSUE #1591: zoomTo does not work after upgrading from version 8.3.0 to 8.4.0
**Describe the bug**

zoomTo does not work after upgrading from version 8.3.0 to 8.4.0

**To Reproduce**

```js
import React, { memo, useCallback } from 'react';
import { TouchableOpacity, Text } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

const Test = () => {
  const camera = React.createRef(null);
  const map = React.createRef(null);
  const zoom = useCallback(
    async (zoomIn) => {
      const currentZoom = await map.current.getZoom();
      camera.current.zoomTo(currentZoom + (zoomIn ? 1 : -1));
    },
    [map, camera]
  );
  const zoomPlus = useCallback(() => zoom(true), [zoom]);
  const zoomMinus = useCallback(() => zoom(), [zoom]);
  return (
    <>
      <MapboxGL.MapView style={styles.map} ref={map}>
        <MapboxGL.Camera ref={camera} />
      </MapboxGL.MapView>
      <TouchableOpacity onPress={zoomPlus}>
        <Text>zoom plus</Text>
      </TouchableOpacity>
      <TouchableOpacity onPress={zoomMinus}>
        <Text>zoom minus</Text>
      </TouchableOpacity>
    </>
  );
};
```

**Versions**
 - Platform OS: [IOS, Android]
 - "react-native": "0.64.2",
 -  "@react-native-mapbox-gl/maps": "8.4.0"

### LINKED ISSUE #1621: Upgrading from v8.2.1 -> 8.4.0 Broke Updating Camera Props
**Describe the bug**  
After upgrading from v8.2.1 -> v8.4.0 update camera props stoped working.  

In iOS updating zoom and heading no longer work after initial load (follow modes do still work however).

In Android, no camera prop updates work after initial load.

**To Reproduce**  
Create MapView map camera tied to a redux store for zoom & heading props.  Outside of the component, have a button to adjust props.  Zoom/Heading fail to update when external button is pressed updating camera props. 

Could be resolved by https://github.com/react-native-mapbox-gl/maps/pull/1619 - but unclear. 

**Expected behavior**  
Map View Zoom & Heading update as expected on prop change to Camera component after initial load.

**Actual behavior**  
Map View Zoom & Heading, and in Android, follow modes etc..., are reflected in Map View after updating the Map Camera.

**Screenshots**  

**Versions (please complete the following information):**  
 - Platform: Android, iOS
 - Platform OS: iOS 15.0
 - Device: iPhone 12
 - Emulator/ Simulator: yes (also failed on real device)
 - Dev OS: OSX 11.6
 - react-native-mapbox-gl: 8.4.0
 - Mapbox GL version: 6.4.1
 - React Native Version 0.66.2

### PR DESCRIPTION
**Pull request by naftalibeder**
## Description

resolves #1591, resolves #1621

## Checklist

- [x] I have run local test cases via `yarn run unittest` (sneaky edit)
- [X] I have tested this on a device/simulator for each compatible OS
- [X] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [X] I updated the documentation with running `yarn generate` in the root folder
- [X] I mentioned this change in `CHANGELOG.md`
- [X] (n/a) I updated the typings files (`index.d.ts`)
- [X] I added/ updated a sample (`/example`)

## Video

https://user-images.githubusercontent.com/2423291/141192218-65c5a003-9a2b-428f-b14f-7f73d49716bf.mov

### CODE REVIEW

**Comment by ferdicus** [comment]
@naftalibeder, looks good to me - I leave the "is it fixed though" comments to the ones affected. 

One more thing though: 
`yarn lint` as well as `yarn unittest` are failing for me locally  

Would you mind rechecking those. 

Thanks in advance

**Comment by kristfal** [comment]
@naftalibeder please check out https://github.com/react-native-mapbox-gl/maps/issues/1591#issuecomment-972798219

I think you may want to revert the changes proposed on JS side and add an explicit check on zoomLevel similar to that comment to allow camera changes that contain nothing but zoomLevel to be passed to native side.

File: javascript/components/Camera.js [hunk 1]
```diff
@@ -278,7 +278,7 @@ class Camera extends React.Component {
     }
 
     if (shouldUpdate) {
-      this._setCamera(cameraConfig);
+      this.setCamera(cameraConfig);
```
Comment (kristfal) [inline javascript/components/Camera.js:281]: These should not change. In case we update the public `setCamera` interface, we want all internal camera code to stay as-is. The fix required to make zoomLevel work from JS is:

add:
```
  _hasZoomLevelChanged(prev, next) {
    if (existenceChange(prev, next)) {
      return true;
    }

    if (!prev && !next) {
      return false;
    }

    return prev !== next;
  }
``` 

Update last part of _handleCameraChange:

```
    const zoomChanged = this._hasZoomLevelChanged(c.zoomLevel, n.zoomLevel);
    const boundsChanged = this._hasBoundsChanged(c.bounds, n.bounds);
    const centerCoordinateChanged = this._hasCenterCoordinateChanged(c, n);
    const paddingChanged = this._hasPaddingChanged(c, n);


    let shouldUpdate = false;
    if (n.bounds && (boundsChanged || paddingChanged)) {
      cameraConfig.bounds = n.bounds;
      shouldUpdate = true;
    } else if (
      n.centerCoordinate &&
      (centerCoordinateChanged || paddingChanged)
    ) {
      cameraConfig.centerCoordinate = n.centerCoordinate;
      shouldUpdate = true;
    } else if (
      zoomChanged
    ) {
      cameraConfig.zoomLevel = n.zoomLevel;
      shouldUpdate = true;
    }

    if (shouldUpdate) {
      this._setCamera(cameraConfig);
    }
```

**Comment by naftalibeder** [comment]
@kristfal 

> add an explicit check on zoomLevel

Sounds good to me. Didn’t catch this because I made the assumption that users are always setting the location of the camera too. I’ll try to take care of this today.

**Comment by kristfal** [comment]
Perfect, yes – I imagine it's a pretty special use-case, but it hit us. 

Could also be we need to do the same for pitch and rotate as well (haven't tested), just to ensure we don't prevent individual props from updating.

**Comment by ferdicus** [comment]
hey @kristfal, great to see you back here :)

File: javascript/components/Camera.js (hunk 1 above)
Comment (naftalibeder) [reply javascript/components/Camera.js:281]: @kristfal 
> In case we update the public setCamera interface, we want all internal camera code to stay as-is

If that's the case, should we change other internal calls to the `_setCamera` version? `this.setCamera` is called locally in a number of places.

**Comment by naftalibeder** [comment]
@kristfal @ferdicus I believe this is fixed.

A number of changes, but the most important one is separating the `bounds`/`centerCoordinates` conditionals from the check on the remaining coordinates (see `Camera.js#L285` - Github's link-to-line isn't working right now).

Whether or not changes in zoom, pitch, etc. cause the camera to update should have nothing to do with whether the camera's coordinates have changed as well. So this should allow any changes to propagate down into the native code.

I made similar changes in the native code, basically to be more forgiving in allowing zoom to be changed (even if bounds was also previously set). It's less "correct", but probably more intuitive.

Let me know what you think!

File: javascript/components/Camera.js (hunk 1 above)
Comment (kristfal) [reply javascript/components/Camera.js]: Internal code should use _setCamera, so if you want to fix that, then awesome!

**Comment by dorthwein** [comment]
Confirming this fixes https://github.com/react-native-mapbox-gl/maps/issues/1621 for us.

**Comment by naftalibeder** [comment]
@dorthwein Fantastic! Thanks for your patience :)

**Comment by naftalibeder** [comment]
@ferdicus seems like this fixes an important issue for a lot of people. Is there anything I can do to help get this merged in? Not sure if it’s waiting for anything else from me.

**Comment by ferdicus** [comment]
@naftalibeder, I'll merge this today, make some (build) tests and create a new release

**Comment by ferdicus** [comment]
looks good, merging

Thanks @naftalibeder

**Comment by danidaryaweesh** [comment]
I'm not able to update the camera zoomLevel on 8.5.0 specifically on iOS after component mount. Is anyone else here experiencing this issue?
